# Generated by Django 5.0.4 on 2024-04-22 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='film',
            name='realisateur',
        ),
        migrations.RemoveField(
            model_name='film',
            name='titre',
        ),
        migrations.AddField(
            model_name='film',
            name='date_de_parution',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='nom',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='note',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
